[run]
build = "npm run build"

[gptengineer-app]
project_id = "da94a754-20c7-4259-a876-9281ced15104"

[[gptengineer-app.openapi]]
url = "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/color.pizza/1.0.0/openapi.yaml"
